config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "people#index"
  resources :people, only: %i[new create show index destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :parent, class_name: 'Person', foreign_key: 'parent_id', optional: true
  has_many :children, class_name: 'Person', foreign_key: 'parent_id'
  has_many :grandchildren, through: :children, source: :children

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @persons = Person.all
  end

  def new
    @person = Person.new
    @person.parent_id = params[:parent_id]
  end

  def show
    @person = Person.find(params[:id])
    @children = @person.children
    @grandchildren = @person.grandchildren
  end

  def create
    @person = Person.new(person_params)
    @person.parent_id = params[:person][:parent_id]

    if @person.save
      redirect_to person_path(@person), notice: 'Person was successfully created.'
    else
      flash[:error] = 'Something went wrong, please provide all the values.'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy!

    redirect_to people_path
  end

  private

  def person_params
    params.require(:person).permit(:name, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VatrenasTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash.any? %>
      <%= render 'shared/flashes' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<div class="people">
  <h1>People in the list</h1>
  <% if @persons.any? %>
    <ul>
      <% @persons.each do |person| %>
        <li>
          <p class="person-name"><%= link_to person.name, person_path(person) %></p>
          <p>
            <%= button_to "Delete",  @person, method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete this person?" } }, class: 'delete-btn' %>
          </p>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>There is no one here yet.</p>
  <% end %>

  <div class="create-link">
    <%= link_to 'Create person', new_person_path %>
  </div>
</div>

app/views/people/new.html.erb
<div>
  <%= form_with model: @person, url: people_path(parent_id: @person.parent_id), class: 'person-form' do |f| %>
    <%= f.hidden_field :parent_id, value: @person&.parent_id %>
    <%= f.text_field :name, placeholder: "Type name..." %>
    <%= f.submit :submit %>
  <% end %>
</div>

app/views/people/show.html.erb
<div class="people">
  <h1>
    <%= @person.name %>
  </h1>

  <div class="family-tree">
    <div class="family">
      <% if @children.any? %>
        <h3>Children</h3>
        <% @children.each do |child| %>
            <p><%= child.name %></p>
        <% end %>
      <% end %>
    </div>

    <div class="family">
      <% if @grandchildren.any? %>
        <h3>Grandchildren</h3>
        <% @grandchildren.each do |grandchild| %>
          <p><%= grandchild.name %></p>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="buttons">
    <div class="create-link">
      <%= link_to "Create a child of #{@person.name}", new_person_path(parent_id: @person.id) %>
    </div>
    <div class="return">
      <%= link_to "Return to dashboard", people_path %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div>
  <% flash.each do |type, msg| %>
    <div class="flash">
      <%= msg %>
    </div>
  <% end %>
</div>